

services:
  - type: web
    name: brasil-burger-symfony
    plan: free
    runtime: docker
    dockerContext: ./BrasilBurger_Symfony
    dockerfilePath: ./BrasilBurger_Symfony/Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Q28lkcThzxRG@ep-withered-surf-a4zfsqbd-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: APP_SECRET
        generateValue: true
      - key: APP_ENV
        value: prod
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,REMOTE_ADDR"
      - key: TRUSTED_HOSTS
        value: "^.*$"
