services:
  - type: web
    name: brasil-burger-manager
    plan: free
    dockerfilePath: ./BrasilBurger_Symfony/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromConfig: DATABASE_URL
      - key: APP_SECRET
        generateValue: true
      - key: APP_ENV
        value: prod
